---
services:
  bobbeh-bot:
    image: bobbehbot:latest
    container_name: bot
    restart: unless-stopped
    environment:
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
      - TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}